### ISSUE TITLE
Problem clearing uploads

### ISSUE THREAD

**Issue by syddm** [VideoGuys/python-client#3]
Everything below was done on vidup. not vev.
So uploads on vidup get stuck all the time, and since you only have five upload slots, anything new can not be uploaded.
I tried using the api to clear uploads older than 30 minutes.
I can get a list of current uploads using:
video_uploads = api_client.getVideoUploads()
then I go though them one by one, and if it's over 30 minutes old I tried deleting it using
deleted_url_upload = api_client.deleteUrlUpload(code)
where code is what is returned by  api_client.getVideoUploads() inside 'code' dictionary key.
But I get an error:
<class 'dict'>: {'code': 400, 'message': 'invalid api route', 'errors': []}
I get the same error if I try to see the upload status:
 url_upload_status = api_client.getUrlUploadStatus('qdmydgze3mz9')
This above is a actual currently existing file code as an example.
Can you take a look at this issue? Maybe something changed in the api since it was written?
Or am I using it wrong?
I really need to be able to clear these stuck uploads, as they are happening way too much lately.

**Comment by VideoGuys** [comment]
I can suggest a couple things as I am not able to reproduce your current issue.
Ensure [get,post,delete] (at minimum) is enabled for your API token.
Ensure you are using the proper function for fetching Uploads and Deleting them, for example, if you are fetching videoUploads and urlUploads clear them with deleteVideoUpload and deleteUrlUpload respectively.
If problems communicating with the API continue get in contact with the site directly just to make sure they can look into the API side of things.

**Comment by syddm** [comment]
You were right. I was mixing api upload and url upload. My bad, deleteVideoUpload is working on the videoUploads list. Thanks for pointing it out.
